settings:
  blacklist_terms: []
  blacklist_urls: []
  data_output_directory: ../../workspace/data/reddit/
  debug: false
  detail: MD
  group_by_source: true
  max_results: 3
  min_age_hours: 12
  min_score: 20
  md_output_directory: ../../workspace/feeds/reddit
  md_log: ../../workspace/data/reddit/log.md

routine:
- detail: SM
  max_results: 2
  min_score: 0
  sort: new
  source: ArtificialInteligence
- detail: XL
  max_results: 3
  min_age_hours: 0
  min_score: 2
  sort: new
  source: MarvelStudiosSpoilers
