settings:
  data_output_directory: ../../workspace/data/reddit/
  debug: false
  detail: MD
  sort: new
  group_by_source: true
  max_results: 3
  md_output_directory: ../../workspace/feeds/reddit
  md_log: ../../workspace/data/reddit/log.md

routine:
- name: "marvel"
  detail: SM
  max_results: 2
  subreddit: ["MarvelStudioSpoilers"]
- name: "max"
  subreddit: MarvelStudiosSpoilers
- detail: LG
  max_results: 3
  sources: 
    - "Marvel comics"
    - "MarvelStudiosSpoilers"
